export const NEW_GAME = 'NEW_GAME'
export const NEW_GAME_COMPLETED = 'NEW_GAME_COMPLETED'
export const NEW_GAME_FAILED = 'NEW_GAME_FAILED'

export const PLAYER_MOVE = 'PLAYER_MOVE'
export const PLAYER_MOVE_COMPLETED = 'PLAYER_MOVE_COMPLETED'
export const PLAYER_MOVE_FAILED = 'PLAYER_MOVE_FAILED'

export const AI_MOVE = 'AI_MOVE'
export const AI_MOVE_COMPLETED = 'AI_MOVE_COMPLETED'
export const AI_MOVE_FAILED = 'AI_MOVE_FAILED'

export const HAS_WINNER = 'HAS_WINNER'
export const NO_WINNER = 'NO_WINNER'
export const WRONG_MOVE = 'WRONG_MOVE'
